openapi: 3.0.1
info:
  version: 0.0.1
  title: SportHub
  description: Swagger for Softserve Project
  termsOfService: http://swagger.io/terms/ # change it
  contact:
    email: enterEmail@please.GGWP # enter our email
  license: # enter our licence
    name: My thorny thoughts, my thorny thoughts # change it
    url: http://www.apache.org/licenses/LICENSE-2.0.html # change it
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/fayon/SportHub/0.0.1
tags: []
paths: {}
components:
  schemas: {}
  securitySchemes:
    sportHub_auth:
      type: oauth2 # maybe can be changed
      flows:
        implicit:
          authorizationUrl: enterAuthorizationUrl
          scopes: {}
    api_key:
      type: apiKey
      name: api_key
      in: header